### ISSUE TITLE
soroban-rpc: add effects/changes a transaction makes over an account in the simulation response

### ISSUE THREAD

**Issue by earrietadev** [stellar/soroban-rpc#11]
### What problem does your feature solve?
The ability to show users what could be the state of their accounts after a transaction has been signed and sent to the network. With Stellar Classic operations was easy to show them all the operations happening on a transaction, but with Soroban transactions is harder since each contract is unique so being able to at least show them something like "XLM: -20,239" could improve the UX and in some way security a lot.

### What would you like to see?
A field in the simulation response similar to the result of the transaction (when transactions return value) but with the calculated simulation effects/changes. My idea is that I could show users something along the lines of "You are authorizing 200 USDC, the simulation result shows you could be charged 100 USDC". I understand the end result could be different, but is still valuable

### What alternatives are there?
Currently, I'm testing to show what is being authorized from the XDR transaction, that still helps with the UX but I think both cases are complementary

**Comment by janewang** [comment]
Is this sufficiently address the blind signing vulnerability, or do we also need to print auth tree(s) in the simulate endpoint on the RPC? I assume that showing the tree requires some core changes. Please weigh in @tomerweller and @leighmcculloch

**Comment by leighmcculloch** [comment]
@2opremio What API are you thinking of?

**Comment by dmkozh** [comment]
FYI I've just introduced some additional info to the response we return from the new `soroban-simulation` library (it would take a bit more time to before RPC starts using the updated library, but the most of the integration work is already done):

- All the diffs to RW ledger entries: https://github.com/stellar/rs-soroban-env/blob/8c9ab83c406bd86f56d52eae3e39dccf6b45b3da/soroban-simulation/src/simulation.rs#L78 . Note, that this might contain no-op changes as well (i.e. when contract writes an entry without changing its contents).
- Emitted contract events: https://github.com/stellar/rs-soroban-env/blob/8c9ab83c406bd86f56d52eae3e39dccf6b45b3da/soroban-simulation/src/simulation.rs#L58. Currently these are also returned as part of diagnostic events, but it would be safer to use a dedicated field (as to not confuse diagnostic events from events hashed into ledger)

The next step would be to propagate these fields into the preflight response.

**Comment by 2opremio** [comment]
> @2opremio What API are you thinking of?

The API at https://github.com/stellar/soroban-rpc/pull/120 :)
