### ISSUE TITLE
Align naming convention to `cursor`

### ISSUE THREAD

**Issue by janewang** [stellar/soroban-rpc#118]
### What problem does your feature solve?
There is some confusion for developers about what is `cursor`. For example in [`getEvents`](https://developers.stellar.org/network/soroban-rpc/methods/getEvents), we call `cursor` in the request and `pagingToken` in the response. 

Discord thread: https://discord.com/channels/897514728459468821/966788672164855829/1222799292344045619

Developers are confusing that `pagingToken` is the `cursor`. We should rename it to `cursor` in the response.

**Comment by janewang** [comment]
Agreed, wait after one or two protocol releases before we remove duplicated field is a great idea.

**Comment by mollykarcher** [comment]
We'd like to consider adding a separate `cursor` field to the top-level response, at the same level as `events`. The value of `cursor` would be the same as the value of the `pagingToken` from the last element in the list of `events`. Note that this format should apply to all future paginated endpoints, not just `events`, and will require updates to our Pagination documentation pages.

**Comment by psheth9** [comment]
Instead of removing `pagingToken` for each events how about we rename `pagingToken` to `eventId`. I believe this id might be useful for devs/clients to uniquely identify events on their end. 

Cursor will still be present as a top level field for pagination purpose.

**Comment by mollykarcher** [comment]
Another recommendation that we can take or leave, given I know we're trying to get this into p22 and I'm not sure how much work it may be. I think we should consider making the `cursor` completely opaque to the client/end-user _and_ encoding the filter/sort information into it.

For example, the `cursor` that the API returns could be a base64 encoded string representation of something like the following dictionary:
```
{
    startLedger: 10,
    endLedger: 20
    event_id: 4000,
    order: desc
}
```

This would give us a couple advantages:
- Future proofs, as the cursor is clearly not an `event_id`, so it prevents clients from relying on it as one, and therefore let's us change it in the future when we need to
- Removes the need for the client to pass in all of their filter params + sort params on every single request. If they have a live `cursor` they effectively have a stateful scroll id that they can use to continue their scrolling session
- If it helps us performance-wise, we could actually effectively change the filter parameters for the next request in the scroll (ex. moving startLedger up)
