### ISSUE TITLE
JSON Support

### ISSUE THREAD

**Issue by janewang** [stellar/soroban-rpc#124]
Developers have the option to request data in JSON format. By default, responses are in the current XDR+JSON format unless specified otherwise in the request. If JSON format is requested, the system will dynamically convert the XDR data to JSON for easier readability and use by developers.

In order to:
- To request JSON format, include `'xdrFormat’: 'json'` in the request.
- To request the current XDR+JSON mixed response (how the API currently returns the response), simply don’t specify the `xdrFormat` in the request, or include `'xdrFormat': 'base64'` in the request. The response will return the current JSON and XDR in base64 string. 

The initial implementation is then backward compatible.

Example Usage for JSON response:

```
curl -X POST \
-H 'Content-Type: application/json' \
-H 'Accept': application/json \
-d '{
 "jsonrpc": "2.0",
 "id": 8675309,
 "method": "simulateTransaction",
 "params": {
   "xdrFormat": "json",
   "transaction": <in JSON>,
   "resourceConfig": {
     "instructionLeeway": 3000000
   }
 }
}' \
https://soroban-testnet.stellar.org:443 | jq
```

We have developed a canonical XDR ⇔ JSON schema for conversion between XDR and JSON: [Stellar JSON](https://docs.google.com/document/d/1fHQxS5ZEt7nwBVZg4qLHpKzKsUXxoF5Et6cFFYqrNMM/edit)

See https://docs.google.com/document/d/1tTuzL7HBHedp9TE-LonD1QV67SaBSReQ8YFj9xQIgtA/edit#heading=h.uedyb8nrk3a9

**Comment by mollykarcher** [comment]
@janewang FYI `unpackxdr` being at the top-level breaks the json-rpc spec. I updated the description here to move it to within `params`. Cool with you?

**Comment by Shaptic** [comment]
@janewang @mollykarcher suggestion: asking the user to pass a parameter `"format": "xdr" | "json"` rather than `unpackxdr`

**Comment by janewang** [comment]
@Shaptic I think that's where we started with. However, the format of the rpc response is technically already in JSON, with XDR strings.

**Comment by Shaptic** [comment]
`xdr_format: "json" | "base64"` then?

**Comment by janewang** [comment]
Fine with preserving the option to unpack XDR to another format. However, I think after we unpack to JSON, convert to other formats should not be the responsibility at this layer. 

I think `xdrFormat`: "json" | "base64" is reasonable.
