### ISSUE TITLE
New DB design document for supporting transactions endpoint

### ISSUE THREAD

**Issue by psheth9** [stellar/soroban-rpc#130]
### What problem does your feature solve?
subtask of https://github.com/stellar/soroban-rpc/issues/115

### What would you like to see?

Design document with new schema of transaction and overview of implementation

**Comment by psheth9** [comment]
Doc here: https://docs.google.com/document/d/1zjtFXfbtjm8vN0BDc5bG5pGEuIGyyf3m9yRWeHsTvWs/edit

**Comment by Shaptic** [comment]
This is complete now, right? We've converged on Approach 3 :ok_hand:
