### ISSUE TITLE
Design: Maintaining retention window asynchronously in the DB

### ISSUE THREAD

**Issue by Shaptic** [stellar/soroban-rpc#153]
There is no `db reingest` equivalent in Soroban RPC. We should discuss the extent to which we want to support managing gaps in the database due to downtime or other inconsistencies. Options include:
  - trimming the database of everything that is not continuous on startup
  - erroring/forcing reingestion of any gaps in the retention window
  - allowing users to reingest arbitrary spans of history and/or to find/fill gaps in existing history like Horizon
  - doing nothing and just forcing users to wait for the retention window to fill before they get continuous history
  - others?

Each of these will result in a different level of work so we should decide first.

**Comment by sydneynotthecity** [comment]
Objective is to write a one-pager outlining design choices and implementation details to maintain db retention window. Implementing the work is out of scope.

**Comment by mollykarcher** [comment]
Closing as a dup of https://github.com/stellar/soroban-rpc/issues/196
