### ISSUE TITLE
soroban-rpc: optimize simulateTransaction by querying ledger entry/expiration at the same time

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-rpc#18]
## Background

In https://github.com/stellar/soroban-tools/pull/916, we combined the database query to retrieve the ledger key + expiration key at the same time ( for code/data entries ). The above PR also updated the RPC calls to return these.

However, the internal usage of simulateTransaction was never taking advantage of that.

## Remaining work

The `SnapshotSourceGet` should be able to return the expiration round as well. That would allow us to make a single query from rust->go instead of two.

**Comment by 2opremio** [comment]
This is done by the `rs-soroban-simulation` library now
