### ISSUE TITLE
Add `getTransactions` to soroban-rpc-client crate

### ISSUE THREAD

**Issue by willemneal** [stellar/soroban-rpc#195]
The new method was recently added (https://github.com/stellar/soroban-rpc/pull/174) but the rust crate needs to be updated to use it.

**Comment by janewang** [comment]
Blocked for now till rpc 21.4.0

**Comment by janewang** [comment]
@BlaineHeffron @willemneal RPC new endpoints are live now on testnet, like `getTransactions`. Platform upgraded the RPC to 21.4.0 this AM.

**Comment by BlaineHeffron** [comment]
Thanks @janewang I'll test it out.

**Comment by BlaineHeffron** [comment]
Fixed by https://github.com/stellar/rs-stellar-rpc-client/pull/3
