### ISSUE TITLE
[epic ] Automatically backfill and reap history

### ISSUE THREAD

**Issue by 2opremio** [stellar/soroban-rpc#196]
Right now there is:

1. No automatic backfill (e.g. if the history is empty on start, it will be filled organically as ledgers close).
2. Very basic reaping. It happens after ingesting every ledger, synchronuously and I am not sure it takes into account any ledgers behind the current history window.

RPC should automatically reconcile the existing history state with the desired state (desired window), accounting for things like changes in the commandline parameters.

RPC should do so asynchronously, in the background without disturbing the normal operation of serving method calls.

Also, RPC should strive to leave the state consistent at all times (e.g. no history gaps should be left as a result of crashes or restarts).

Subtasks (by dependency order):

1. https://github.com/stellar/soroban-rpc/issues/199 (dealing with different window sizes is too complicated)
1. https://github.com/stellar/soroban-rpc/issues/200
1. https://github.com/stellar/soroban-rpc/issues/204
1. https://github.com/stellar/soroban-rpc/issues/203
1. https://github.com/stellar/soroban-rpc/issues/201
1. https://github.com/stellar/soroban-rpc/issues/202
1. https://github.com/stellar/soroban-rpc/issues/205

**Comment by mollykarcher** [comment]
I'm going to close all these issues. We're unsure of the product need. Will recreate if/when we decide to move forward

**Comment by sreuland** [comment]
a year later..the need for this backfill is re-surfacing and may want to reconsider re-opening this ticket. Currently driven by ops use case for horizontal scaling, https://github.com/stellar/ops/issues/3844#issuecomment-3053021648, they would like to do automated scaling of rpc instances, but current pro-longed backfill times are a deterrent.
