### ISSUE TITLE
transactionHandler's GetLedgerRange is not accurate

### ISSUE THREAD

**Issue by 2opremio** [stellar/soroban-rpc#208]
It uses the meta table and not the transaction table. The meta table can have a longer history than the transaction table since it stores the maximum range of the events storage window and the transaction storage window.

Also, `GetLedgerRange` is untested. A test should be added since the function is pretty complex.

The problem was introduced in https://github.com/stellar/soroban-rpc/pull/174

**Comment by 2opremio** [comment]
Also, we will need to revive the old `LedgerRangeGetter` and add the event range like we used to.

**Comment by 2opremio** [comment]
Finally `GetLedgerRange` is overkill if we only want the Latest Ledger sequence, we can use `GetLatestLedger` for that

**Comment by aditya1702** [comment]
> Finally `GetLedgerRange` is overkill if we only want the Latest Ledger sequence, we can use `GetLatestLedger` for that.

@2opremio We want both `latestLedger` and `oldestLedger` along with their details. I think that is why @Shaptic added this method.

**Comment by 2opremio** [comment]
> @2opremio We want both `latestLedger` and `oldestLedger` along with their details. I think that is why @Shaptic added this method.

Not for every endpoint (look at the current uses of `GetLedgerRange`)
