### ISSUE TITLE
soroban-rpc: create grafana dashboard

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-rpc#22]
### What ?

The goal of this task is to create a grafana dashboard that would give us monitoring capabilities of the deployed servers.

**Comment by aditya1702** [comment]
The dashboard has been updated to show the relevant metrics - https://grafana.stellar-ops.com/d/ut9rEquVz/soroban-rpc?orgId=1

Ops will figure out how to publish it to public Grafana this week. And the JSON has already been added to puppet - https://github.com/stellar/puppet-v4/pull/3694
