### ISSUE TITLE
Remove usage of internal `stellar/go/support/errors `

### ISSUE THREAD

**Issue by psheth9** [stellar/soroban-rpc#266]
Linter Error: Do not use stellar/go/support/errors, use the standard 'errors' package and fmt.Errorf()." (forbidigo)

We have different variants of error handling in RPC, we need unified pattern either to rely solely on internal `/support/errors `package or Go's standard` /error` package. We could also tune linter to not report error if internal `/error` package is being used.

**Comment by 2opremio** [comment]
I don't think we should use Stellar's support package since the stdlib supplies everything we need. Adding an extra abstraction layer doesn't add any value IMO

**Comment by psheth9** [comment]
Yeah that's reasonable !! Agree with that.

Okay I am changing this issue detail to get rid of internal `/errors` package usage in RPC code
