### ISSUE TITLE
Test `events` + `Txns` DB changes on AWS

### ISSUE THREAD

**Issue by aditya1702** [stellar/soroban-rpc#281]
- We want to release the events changes but before doing that, need to test its robustness on AWS setup.
- With the retention window increasing to 7 days, we also want to get an idea of the DB space taken by the new transactions and events tables

**Comment by psheth9** [comment]
This is going to be validation of` events+txn` changes for larger retention window just fyi

**Comment by mollykarcher** [comment]
Plan as of right now is:
- Complete performance testing / benchmarking for 1 day of retention 
- Issue RPC release
- Complete performance testing / benchmarking for 7 days of retention
- Change configuration on SDF's instances to 7 day of retention
- (with p22 changes) Change default retention window to 7 days
