### ISSUE TITLE
Get all storage from a contract

### ISSUE THREAD

**Issue by tupui** [stellar/soroban-rpc#293]
I am looking for a way to get all the storage (persistent in that case, but could be other) from a contract using a RPC call.

I've tried with Stella and it gave me the following https://discord.com/channels/897514728459468821/1265827786111586344/1284237847674753211

But this seems to only give me the admin storage key/val, not the rest.

I am trying to get all this basically https://stellar.expert/explorer/testnet/contract/CAP52ERGUZ65UNPHP36CQBHYUPEUG2TT4NPVEV7CREWRT7UCPD7PRWEE/storage

I could scrap that page, but I don't think it's the right approach and would incur load on stellar.expert for nothing. I suppose explorers are using a DB to get all that?

**Comment by tomerweller** [comment]
RPC's design philosophy is to be a minimal and sufficient building block for building soroban apps (and stellar apps in general in the future). "Building block" is key here - it is not meant to be your full backend. Different apps have different data requirements and it's up to their developers and indexing platforms to cater to these.  

Providing all storage associated with a contract efficiently would require adding an additional index in RPC. I think that's going too far in the indexing direction. Not to mention that often times apps would require additional filtering and sorting on top of just fetching data so this is a slippery slope (we know that from our horizon experience).

If you don't want to deploy your own solution I would look into integrating with indexers or block explorers in the ecosystem. (I'm sure orbit would love to give access to his indexed data via api, if it's not already available)

**Comment by tupui** [comment]
Thanks for taking the time to answer 🙇 😃 

I understand and can now see the constraints 👍 I will close the issue then.

From the discussion on discord, I could find another solution to my specific problem. People can register a project, which creates a storage entry, and I wanted to get all entries to have a search on the frontend. Instead I have a contract function which returns true if an entry exits. That works for me now, though it only find exact match. I have a featured section which is manually defined, so I search there first, then go on-chain. I will look into indexes if I need to reevaluate in the future 😄
