### ISSUE TITLE
soroban-rpc: rename `simulateTransaction` to `preflight`

### ISSUE THREAD

**Issue by tomerweller** [stellar/soroban-rpc#41]
[see discussion](https://discord.com/channels/897514728459468821/1037416757972979732/1037416757972979732)

**Comment by mollykarcher** [comment]
@janewang do you think this is something that we still want to do? Or should we close this?

**Comment by janewang** [comment]
Yes we could keep `simulateTransaction`. I will open a doc ticket to align from the docs.
