### ISSUE TITLE
soroban-rpc: Replace `getLedgerEntry` with `getLedgerEntries`

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-rpc#48]
### What problem does your feature solve?

Currently, to fetch multiple ledger entries you have to issue multiple `getLedgerEntry` calls, and you might get them as of multiple ledger states.

### What would you like to see?

Replacing:
```ts
getLedgerEntry(key: xdr.LedgerKey): {
  xdr: xdr.LedgerEntryData,
  lastModifiedLedgerSeq: number,
  latestLedger: number,
}
```
with:
```ts
getLedgerEntries(keys: xdr.LedgerKey[]): {
  entries: (null | {
    xdr: xdr.LedgerEntryData,
    lastModifiedLedgerSeq: number
  })[],
  latestLedger: number,
}
```
If any of the keys are not found they should be put as `null` into the output fields. This is so the client can pair up the requested keys with their results.

We will need to:
- [ ] Add the new method, and deprecate the old one in the first release.
- [ ] Remove the old method in the next release.
- [ ] Update soroban-cli
- [ ] Update js-soroban-client
- [ ] Update soroban-docs
- [ ] Update system-test

**Comment by mollykarcher** [comment]
Closing in favor of https://github.com/stellar/soroban-rpc/issues/28
