### ISSUE TITLE
Remove legacy incorrect cost object from simulateTransaction endpoint

### ISSUE THREAD

**Issue by janewang** [stellar/soroban-rpc#66]
The `simulateTransaction` endpoint currently returns [legacy cost object](https://developers.stellar.org/docs/data/rpc/api-reference/methods/simulateTransaction) that is incorrect in values and confusing to developers. The correct resource costs are in the transactionData XDR. We should remove the legacy cost object. 

Discord thread: https://discord.com/channels/897514728459468821/1194690264225292309

Scope of this work should include sending out the community issue for the breaking change with the [stellar-community-issue-cli](https://github.com/stellar/stellar-community-issue-cli)

**Comment by mollykarcher** [comment]
We're deferring this until p22 since it is a breaking api change

**Comment by 2opremio** [comment]
> that is incorrect in values

Worth noting that it wasn't incorrect in values, it was just not the resources needed for transaction submission but the actual cost of simulation.
