### ISSUE TITLE
reinstate cli_test

### ISSUE THREAD

**Issue by mollykarcher** [stellar/soroban-rpc#85]
### What problem does your feature solve?

As part of resolving the issues with the release pipelines, we removed `cmd/soroban-rpc/internal/test/cli_test.go` [here](https://github.com/stellar/soroban-rpc/pull/68) from the RPC repo, but did not add them back anywhere. We're now in a state where we've lost this test coverage and need to reinstate it where ever it is appropriate to do so.

### What would you like to see?

The tests in this suite exercise the CLI and test certain functionality of the RPC service. It should be our goal that no tests in the `soroban-rpc` repo rely on a client of RPC, as RPC is the upstream dependency. 

While we could blindly add them into the `soroban-cli` repo, we need to make sure that the functionality that they were testing (of the RPC) is still covered by unit/integration tests in this repo, and that we're not losing overall coverage. 

We'll probably need to assess on a test-by-test basis where they should go. For example:
- some may get rewritten as integration tests in `soroban-rpc` without utilizing the `soroban-cli`
- some may simple be moved over to the `soroban-cli` and test against a tagged/released version of `soroban-rpc`
- some may make more sense to be rewritten as a `system-test`

Depending on how in-depth this ends up being, we may want to break this out into separate issues to tackle any test rewrites that need to happen.

**Comment by willemneal** [comment]
Currently https://github.com/stellar/soroban-cli/pull/1202, moves all those tests (minus a few written in go) to use quickstart. The hard part with testing without the CLI is that the RPC crate doesn't have signing and other tools needed to be useful.

So I suggest we create a new crate similar to the JS's `stellar-sdk`, which provides more functionality on top of the RPC crate. This way the CLI could depend on it and then it becomes simpler and allows for written useful rust applications using RPC.

**Comment by psheth9** [comment]
Notes:

I went over most of the tests of `cli_test.go` and majorly all the tests are validating flows around deploying and invoking contracts and the ideal place for it is in `soroban-cli` repository imo. 

Functions from soroban-rpc that were being used by this integration suit are `getLedgerEntry` and `sendTransaction`.
We already have enough test coverage for those in current unit/integration tests (i.e check get_ledger_entry_test and transaction_test)

All in all, soroban-rpc test coverage is not impacted with the removal of `cli_test.go`

**Comment by willemneal** [comment]
I agree, however, we have no tests for the rust crate. I can add this with my current work #101. Even if they are just some sanity checks.

**Comment by psheth9** [comment]
@willemneal  Awesome !! Yes please add those for rust crate

**Comment by psheth9** [comment]
Closing this ticket as test coverage of RPC is not impacted by removing `cli_test` and ideal place for the tests going to be CLI repo. 

Created this issue https://github.com/stellar/soroban-cli/issues/1271 @willemneal Please feel free to update it with anything related to tests around CLI. I know you are already tracking some of it here [#101](https://github.com/stellar/soroban-rpc/pull/101)
