### ISSUE TITLE
Add profiler to see memory stats by in-memory storage (eventStore and Txn Store)

### ISSUE THREAD

**Issue by psheth9** [stellar/soroban-rpc#9]
### What problem does your feature solve?
Currently there is no easy way to find out the impact on memory usage while making changes to in-memory store such as updating retention window or perf improvements

### What would you like to see?
memory dump which can be analyzed further by `go tool pprof` and memory stats like `in-use heap and alloc`

### What alternatives are there?

Run rpc on docker and analyze using linux `htop` command. (still time consuming when it comes to increasing retention window >= 24hrs)

**Comment by psheth9** [comment]
Memory Usage for txn retention window of 2 hours and 24 hours:

I ran memory profiling code by downloading ledger files using LedgerExporter and used it for ingestion. 

A.  **2 hour window: 479 MB**

![image](https://github.com/stellar/soroban-rpc/assets/124409873/4886f842-358b-478e-ad6a-24f42107d91b)


B. **24 hour window: 907 MB**

![image](https://github.com/stellar/soroban-rpc/assets/124409873/bbeed684-7b74-4416-9518-21f63b76ba94)


Note: Files from Ledger exporter does not seem to include events, so memory of event store is not contributing heavily for above numbers but still useful to understand the uptick when we increase the Txn retention window from 2 hour to 24 hours.

**Comment by ire-and-curses** [comment]
Interesting - why is it that this doesn't increase linearly?

**Comment by psheth9** [comment]
Closing this as we are transitioning from in-memory store to DB with the new design

Context: https://github.com/stellar/soroban-rpc/issues/115 and [the analysis document](https://docs.google.com/document/d/1NSrOuogVTHKTk1QLuMS-d4u-aT20ZeAzIJqiqPn0RHg/edit#heading=h.1my3tarepa0c)
